---
# Deployment for Ghost
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
  labels:
    app: ghost
    tier: application
spec:
  selector:
    matchLabels:
      app: ghost
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ghost
        tier: application
    spec:
      containers:
      - name: ghost
        image: ghost:5.14.1
        env: # The variables below could be set on a ConfigMap object
        - name: NODE_ENV
          value: development
        - name: url
          value: http://localhost:8000
        - name: database__client
          value: mysql
        - name: database__connection__host
          value: mysql-service
        - name: database__connection__user
          value: ghostuser
        - name: database__connection__password
          value: "123456"
        - name: database__connection__database
          value: ghost
        ports:
        - containerPort: 8000