---
# Persistent Volume Claim for Ghost pod
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-pv-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
