---
# Deployment for Ghost
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
  namespace: default
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: ghost:5.14.1
          env: # The variables below could be set on a ConfigMap object
            - name: url
              value: "http://{{ ghost_ip }}:{{ ghost_port }}/"
            - name: database__client
              value: "{{ database_client }}"
            - name: database__connection__host
              value: "{{ database_connection_host }}"
            - name: database__connection__user
              value: "{{ database_connection_user }}"
            - name: database__connection__password
              value: "{{ database_connection_password }}"
            - name: database__connection__database
              value: "{{ database_name }}"
            - name: mail__transport
              value: "SMTP"
            - name: mail__options__service
              value: "Mailgun"
            - name: mail__options__auth__user
              value: "{{ mail_auth_user }}"
            - name: mail__options__auth__pass
              value: "{{ mail_auth_pass }}"
            - name: mail__from
              value: "Ghost Support"
          ports:
            - containerPort: 2368
