---
# Playbook to create GKE cluster

- name: Create a GKE cluster
  hosts: localhost # Host to run the tasks on
  gather_facts: false # Do not gather facts
  roles:
    - gke_cluster_create # Role to run
