---
# Playbook to deploy Ghost and its components

- name: Deploy ghost
  hosts: localhost # Host to run the tasks on
  gather_facts: false # Do not gather facts
  roles:
    - deploy_ghost # Role to run
