---

- name: MySQL persistent volume claim
  ansible.builtin.command:
    argv: ["kubectl", "apply", "-f", "~/k8/mysql/mysql-pvc.yml"]

- name: MySQL kubernetes deployment
  ansible.builtin.command:
    argv: ["kubectl", "apply", "-f", "~/k8/mysql/mysql-deployment.yml"]

- name: MySQL kubernetes service
  ansible.builtin.command:
    argv: ["kubectl", "apply", "-f", "~/k8/mysql/mysql-service.yml"]

- name: Ghost kubernetes deployment
  ansible.builtin.command:
    argv: ["kubectl", "apply", "-f", "~/k8/ghost/ghost-deployment.yml"]

- name: Ghost kubernetes service
  ansible.builtin.command:
    argv: ["kubectl", "apply", "-f", "~/k8/ghost/ghost-service.yml"]