---

- name: MySQL persistent volume claim
  when: "delete_data is defined and delete_data == 'true'"
  kubernetes.core.k8s:
    state: absent
    src: k8/mysql/mysql-pvc.yml

- name: MySQL kubernetes deployment
  kubernetes.core.k8s:
    state: absent
    src: k8/mysql/mysql-deployment.yml

- name: MySQL kubernetes service
  kubernetes.core.k8s:
    state: absent
    src: k8/mysql/mysql-service.yml

- name: Ghost kubernetes service
  k8s:
    state: absent 
    src: k8/ghost/ghost-service.yml

- name: Ghost kubernetes deployment
  kubernetes.core.k8s:
    state: absent
    src: k8/ghost/ghost-deployment.yml

- name: Wait for services to be undeployed
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    namespace: default
  register: services
  until: services.resources | length == 1  # only kubernetes service running
  delay: 10
  retries: 5
