---

- name: MySQL persistent volume claim
  kubernetes.core.k8s:
    state: absent
    src: k8/mysql/mysql-pvc.yml

- name: MySQL kubernetes deployment
  kubernetes.core.k8s:
    state: absent
    src: k8/mysql/mysql-deployment.yml

- name: MySQL kubernetes service
  kubernetes.core.k8s:
    state: absent
    src: k8/mysql/mysql-service.yml

- name: Ghost kubernetes deployment
  kubernetes.core.k8s:
    state: absent
    src: k8/ghost/ghost-deployment.yml

- name: Ghost kubernetes service
  k8s:
    state: absent
    src: k8/ghost/ghost-service.yml
