---
- name: Create Google Kubernetes Engine Cluster
  gcp_container_cluster:
    name: ascn-cluster # Name of the cluster
    initial_node_count: "{{ gcp_initial_node_count }}" # Number of nodes in the cluster
    node_config:
      machine_type: "{{ gcp_machine_type }}" # Type of the machine
      disk_size_gb: "{{ gcp_disk_size_gb }}" # Size of the disk
      image_type: "{{ gcp_image_type }}" # Type of the image
    location: "{{ gcp_zone }}" # Zone of the cluster
    project: "{{ gcp_project }}" # Project of the cluster
    auth_kind: "{{ gcp_auth_kind }}" # Authentication method
    service_account_file: "{{ gcp_cred_file }}" # Path to the service account file
    state: present # State of the resource
  register: cluster # Variable to store the result
  until: "cluster is not failed" # Condition to wait for
  delay: 60 # Delay between attempts
  retries: 1 # Number of attempts

- name: Verify that the cluster was created # Verifies that the cluster was created
  shell: gcloud container clusters describe  --project="{{ gcp_project}}"  --zone="{{ gcp_zone }}"  ascn-cluster # Command to run
  register: results # Variable to store the result

- name: Verify that the command succeeded # Verifies that the command succeeded
  assert:
    that:
      - results.rc == 0 # Condition to check

- name: Create a node pool
  gcp_container_node_pool:
    name: default-pool # Name of the node pool
    initial_node_count: "{{ gcp_initial_node_count }}" # Number of nodes in the node pool
    cluster: "{{ cluster }}" # Cluster to add the node pool to
    config:
      machine_type: "{{ gcp_machine_type }}" # Type of the machine
      image_type: "{{ gcp_image_type }}" # Type of the image
      disk_size_gb: "{{ gcp_disk_size_gb }}" # Size of the disk
    location: "{{ gcp_zone }}" # Zone of the node pool
    project: "{{ gcp_project }}" # Project of the node pool
    auth_kind: "{{ gcp_auth_kind }}" # Authentication method
    service_account_file: "{{ gcp_cred_file }}" # Path to the service account file
    state: present # State of the resource

- name: Connect to the cluster (update kubeconfig)"
  shell: gcloud container clusters get-credentials  --project="{{ gcp_project}}"  --zone="{{ gcp_zone }}"  ascn-cluster # Command to run
