---
- name: Refresh inventory
  meta: refresh_inventory # Refreshes the inventory

- name: Check that you can connect (GET) to Ghost and it returns a status 200
  ansible.builtin.uri:
    url: "http://{{ ghost_ip }}:{{ghost_port}}/" # URL to check
    method: GET # Method to use
    status_code: 200 # Status code to check
  register: result # Variable to store the result
  until: result.status == 200 # Condition to wait for
  retries: 10 # Number of attempts
  delay: 5 # Delay between attempts
